import bomb from "@/assets/resources/bomb.svg";
import bullseye from "@/assets/resources/bullseye.svg";
import flip from "@/assets/resources/flip.svg";
import rocket from "@/assets/resources/rocket.svg";
import { v4 } from "uuid";

export const RECENT_GAMES = [
  {
    id: v4(),
    username: "magenta...",
    bet_amount: 290,
    multiplier: 0.0,
    game_name: "Mines",
    payout: 0,
    icon: bomb,
  },
  {
    id: v4(),
    username: "magenta...",
    bet_amount: 290,
    multiplier: 0.0,
    game_name: "Plinko",
    payout: 0,
    icon: bullseye,
  },
  {
    id: v4(),
    username: "magenta...",
    bet_amount: 290,
    multiplier: 0.0,
    game_name: "Flip",
    payout: 0,
    icon: flip,
  },
  {
    id: v4(),
    username: "magenta...",
    bet_amount: 290,
    multiplier: 0.0,
    game_name: "Limbo",
    payout: 25,
    icon: rocket,
  },
  {
    id: v4(),
    username: "magenta...",
    bet_amount: 290,
    multiplier: 0.0,
    game_name: "Mines",
    payout: 0,
    icon: bomb,
  },
  {
    id: v4(),
    username: "magenta...",
    bet_amount: 290,
    multiplier: 0.0,
    game_name: "Plinko",
    payout: 0,
    icon: bullseye,
  },
  {
    id: v4(),
    username: "magenta...",
    bet_amount: 290,
    multiplier: 0.0,
    game_name: "Flip",
    payout: 0,
    icon: flip,
  },
  {
    id: v4(),
    username: "magenta...",
    bet_amount: 290,
    multiplier: 0.0,
    game_name: "Limbo",
    payout: 25,
    icon: rocket,
  },
  {
    id: v4(),
    username: "magenta...",
    bet_amount: 290,
    multiplier: 0.0,
    game_name: "Mines",
    payout: 0,
    icon: bomb,
  },
  {
    id: v4(),
    username: "magenta...",
    bet_amount: 290,
    multiplier: 0.0,
    game_name: "Plinko",
    payout: 0,
    icon: bullseye,
  },
  {
    id: v4(),
    username: "magenta...",
    bet_amount: 290,
    multiplier: 0.0,
    game_name: "Flip",
    payout: 0,
    icon: flip,
  },
  {
    id: v4(),
    username: "magenta...",
    bet_amount: 290,
    multiplier: 0.0,
    game_name: "Limbo",
    payout: 25,
    icon: rocket,
  },
];
